# Generated by Django 3.2.5 on 2021-07-26 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_available',
            new_name='active',
        ),
    ]
